services:
  redis:
    container_name: redis
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - postgres_network

  postgres_master:
    container_name: postgres_master
    image: postgres:16.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_master_data:/var/lib/postgresql/data
    networks:
      - postgres_network
    command: >
      postgres

networks:
  postgres_network:

volumes:
  postgres_master_data:
